### ISSUE TITLE
Request - also mailed

### ISSUE THREAD

**Issue by Remzi1993** [centminmod/centminmod#131]
@centminmod 

Hi George

How are you?
I saw that you forked the open source project I maintain (https://github.com/Remzi1993/jquery-manager) and I was just curious how you use the WP plugin and if you would like to help with development?

A couple of weeks ago the project/plugin was accepted on wp.org, see: https://wordpress.org/plugins/jquery-manager/
I would like to find developers who like to maintain a project because I'm very busy and by myself, I'm unable to implement new features or fixes in a timely manner.

Kind regards,

Remzi Cavdar
ict@remzi.info

**Comment by centminmod** [comment]
Hi Remzi thanks for considering me. Unfortunately I am no PHP coder so wouldn't be able to fully maintain such a project. I forked jquery-manger after one of my Centmin Mod users gave me a heads up about your wonderful jquery-manger plugin on my forums [here](https://community.centminmod.com/threads/wordpress-jquery1-12-4-vulnerability.17454/) and [here](https://community.centminmod.com/threads/wordpress-jquery1-12-4-vulnerability.1745).

You can see my forked changes last at v1.7.8 https://github.com/Remzi1993/jquery-manager/compare/master...centminmod:centminmod

basic changes didn't involve any php coding and were

1. update to jquery 3.4.1 as at the time you were using 3.3.1 but since you updated to 3.4.1 my fork wasn't really required anymore so my fork's development ends at v1.7.8
2. update jquery files with patched versions from https://github.com/DanielRuf/snyk-js-jquery-174006 for CVE-2019-11358 - prototype pollution vulnerability fixes in jquery 1.12.4, 2.2.4 and 3.3.1
3. add precompressed gzip & brotli versions of jquery for nginx - allow nginx gzip_static directive to serve the precompressed gzip & brotli versions when nginx web server supports it

I do hope you find someone to maintain the project because it's a wonderful addition to wordpress for what it can do :)

cheers

George

**Comment by Remzi1993** [comment]
Hi George,
Thanks for your reply. Could you ask around? I still maintain this project, but I would like to maintain it with more developers.

In the meantime, I will keep track of the jQuery versions and update the plugin asap.
I will redirect users to wp.org at https://wordpress.org/plugins/jquery-manager/ (it's more straightforward and simple for them than GitHub for non techy users)
 
Thank you for the information. Do you have more feedback? Or questions?

Cheers,
Remzi

**Comment by centminmod** [comment]
Will ask around already posted on my forums https://community.centminmod.com/threads/wordpress-jquery1-12-4-vulnerability.17454/page-3#post-75535.

as to feedback / questions, don't have any right now 

all the best

George

**Comment by Remzi1993** [comment]
Hi @centminmod 
I have also made a statement, see: https://github.com/Remzi1993/jquery-manager/issues/12
