### ISSUE TITLE
Sendmail or no email

### ISSUE THREAD

**Issue by Stonedestroyer** [centminmod/centminmod#133]
**Bug Report Forums**

* Check the official Centmin Mod Community's [Bug Report Forum](https://community.centminmod.com/forums/bug-reports.12/) to see if the bug has already been reported/resolved. 

**Background Information**

Please fill in any relevant information that applies to you:

* **CentOS Version:** i.e. CentOS 6 32bit or 64bit / CentOS 7 64bit ?
CentOS 7 x64
* **Centmin Mod Version Installed:** i.e. 123.08stable or 123.09beta01
123.09beta01 
* **Nginx Version Installed:** i.e. 1.15.12. Can find version via command `nginx -v`
* **PHP Version Installed:** i.e. 5.6.40, 7.0.33, 7.1.28, 7.2.17, 7.3.4. Can find version via command `php -v`
* **MariaDB MySQL Version Installed:** i.e. 10.0.x or 10.1.xx or 10.2.xx or 10.3.xx. . Can find version via command `mysqladmin ver`
* **When was last time updated Centmin Mod code base ? :** i.e. run centmin.sh menu option 23 submenu option 2 or cmupdate command
* **Persistent Config:** Do you have any persistent config file options set in `/etc/centminmod/custom_config.inc` ? You can check via this command: `cat /etc/centminmod/custom_config.inc` and post output using [markdown CODE](https://guides.github.com/features/mastering-markdown/).
```
SENDMAIL_INSTALL='y'         # Install Sendmail (and mailx) set to y and POSTFIX_INSTALL=n for sendmail
POSTFIX_INSTALL=n            # Install Postfix (and mailx) set to n and SENDMAIL_INSTALL=y for sendmail
LETSENCRYPT_DETECT='y'
```

* **Install Method:** How was Centmin Mod installed ? Exact specific steps or commands used.

**Describe the bug**
A clear and concise description of what the bug is. With exact SSH commands and/or steps used if applicable.

Sendmail not installed.

**Expected behavior**

Sendmail installed and postfix not installed. 

**Additional context**

If possible I wish to not install sendmail or postfix at all. Is this possible to do? As I will replace the sendmail binary and change in php.ini to another one that is neither of those. The reason I wanted sendmail is cause it wouldn't break as hard as postfix does in the scripts when running centmin.

**Comment by centminmod** [comment]
Yeah it's been years since sendmail MTA install has been actually tested as default and focused development has been on postfix MTA defaults, so yes it could be possible that sendmail MTA isn't working. But if you have problems with postfix, you should report those in Bug report forum https://community.centminmod.com/forums/bug-reports.12/ as I haven't had issues with postfix on centmin mod in over 8+ yrs. But I may not be using same scripts you do - hence would need folks to report issues. So if you outline exact examples/errors you get with postfix and your scripts - reporting on community forum will probably get more eyeballs and potential solutions on your issue as opposed to on github issue tracker as more community forum members may have come across your exact issues and offer up their own solutions too.

Or are you modifying postfix config afterwards yourself further ?

Right now you can't NOT install Postfix MTA by default. If you don't use it you can just stop the service

```
service postfix stop
chkconfig postfix off
```
that will stop postfix and also prevent it from starting up on system reboots.

CSF Firewall however has postfix rules in place which will still be there for some ports.

**Comment by Stonedestroyer** [comment]
I'm using Surgemail so my need for postfix is not necessary. As surgemail replaces sendmail binary. 

I will try disable it and see if that can work with it.

**Comment by Stonedestroyer** [comment]
Disabling postfix did the trick.
