### ISSUE TITLE
Feedback and suggestions

### ISSUE THREAD

**Issue by rrjanbiah** [centminmod/centminmod#145]
Recently installed a WordPress in DigitalOcean using Centmin Mod `betainstaller72.sh`. The final WordPress is butter smooth. But, I noticed few items that the installer can add or improve: 

- [ ] Simplify the home page. Currently there are too many options. Probably show the installer command above the fold with just 2 options: stable and beta.
- [ ] There are so many documentation available. It is good. But, at the same time it is confusing (Not sure which one is latest). Suggestion here: Add some inline documentation to the installer script
- [ ] When terminating the script in the middle (due to some confusion during the process, say when installing WordPress options), the cursor goes off - perhaps #110 
- [ ] For installing WordPress, it is not clear if we have to choose option `2` first. If we choose option `2` and then choose `22`, installer doesn't proceed. (Correct procedure is to choose option `22` only)
- [ ] Letsencrypt provides 4 options and not clear which one to choose. Perhaps it has some role in having https only domain? Similar to WordPress caching options, provide the recommended option and provide inline documentation.
- [ ] https only domain seems to need manual tweak. (In my setup, it allows both http and https.) Add it in the installer itself.
- [ ] Instead of config files, get those options in the installer itself. In case, if that will take more time to implement a web based wizard script to download the config file.
- [ ] Before starting the installer script, ask for some confirmation and provide rough ETA and disk consumption (Currently it takes around 50 minutes)
- [ ] 1-click DigitalOcean installer will be greatly helpful (https://github.com/centminmod/centminmod/projects/1#card-20100929)
- [ ] For protecting WordPress, adding password protection to the `wp-login.php` is good. But, `Hide My WP Ghost – Security Plugin` seems better option as it completely hides.
- [ ] In some places, `Optimus` is used instead of `Autoptimize`
- [ ] In WordPress, instead of prompting with `To complete setup`, provide minor options in the installer itself and set up recommended options.

**Comment by centminmod** [comment]
@rrjanbiah thanks for taking the time to provide some feedback and suggestions :)

* home page documentation is indeed need of an overhaul
* as there are some inline help/info in some places for centmin.sh menu but not for installation itself right now
* cursor off screen probably specific to your SSH client config too. What SSH client you using ? what is output for this command when you're logged into SSH for the server = `env | egrep 'TERM|LANG'`
* yeah some inline info for letsencrypt choices might be nice
* strange for https only mode, is the primary domain www or non-www? what tweak did you do?
* instead of config files? which config files you referring to ? you mean persistent config file `/etc/centminmod/custom_config.inc ` ? those variables all correspond with variables in centmin.sh itself but they can be override when you update centmin mod, so hence persistent config file at `/etc/centminmod/custom_config.inc ` which persists
* hard to provide ETA as it ultimately depends on server hardware and configure itself and disk speed and that can vary greatly between web hosts' servers
* 1-click DO yes would be great. I sort of let that slip by as DO response time to my questions and support for 1-click related developments have been slow - some replies taken several months to reply and even had one over 1 yr. Doesn't give me much confidence if offering Centmin Mod 1-click if end user experienced issues that I or DO need to resolve are not done in a timely manner. Something I'll need to revisit and re-evaluate
* Hiding logins might work for some but might break other folks intended usage, so usually that is left to end users to decide
* Complete setup rules are left to end user so as least they know what's needed to be done as it can be end user subjective to their usage i.e. their permalinks structure which they may want to do differently and would need to know where that is done

**Comment by rrjanbiah** [comment]
@centminmod Thank you so much for your quick reply

> cursor off screen probably specific to your SSH client config too. What SSH client you using ? what is output for this command when you're logged into SSH for the server = env | egrep 'TERM|LANG'

I'm on Ubuntu MATE (16.04), using command line `ssh`. Here's the output for `env | egrep 'TERM|LANG'`:
```
TERM=xterm
LANG=en_IN
```

> strange for https only mode, is the primary domain www or non-www? what tweak did you do?

I've installed it in subdomain. No tweak done yet. Noted https://centminmod.com/nginx_domain_dns_setup.html#httpsredirect and yet to try that.

> instead of config files? which config files you referring to ? you mean persistent config file `/etc/centminmod/custom_config.inc` 

Yes, I meant `/etc/centminmod/custom_config.inc`. I understand that it is for persistence. But, this looks too technical. Probably a web based wizard to generate the config file may at least help.

> 1-click DO yes would be great. I sort of let that slip by as DO response time to my questions and support for 1-click related developments have been slow - some replies taken several months to reply and even had one over 1 yr. 

Can't really understand the challenges. It is just installing some defaults and offering the 'snapshot' image for the 1-click install. Probably you may have tried to offer all feature set within this image


Also, FWIW... I have noted that the centminmod is full documentations with excessive comparisons, benchmarking, etc. I'm not sure about the conversion though. IMHO, if it focuses some niche area like databases, distributed databases, Rust, etc, it may get much more conversion. (Sorry, but thought of sharing this perspective... as there seems to be too much efforts are been invested)

**Comment by rrjanbiah** [comment]
*Additional note*

The https only domain was working when installing the vhost using option `2`. I also don't remember that the Letsencrypt was offering 4 options as in the option `22`
