### ISSUE TITLE
Converting bash script into Ansible playbook

### ISSUE THREAD

**Issue by nlemoine** [centminmod/centminmod#37]
Hi, 

Have you considered converting the whole bash script into an Ansible playbook? 
There are good tools outhere (Chef, Ansible, Puppet) that can bring server installation/configuration automation further. 

I see various benefits:
- No need to do anyhting on the remote server, everything can be handled from your local computer
- Script be run at once and configure multiple servers
- Less and more structured code

From what I've read, Ansible seems the best candidate as it does not require installing extra software on the remote machine.

**Comment by guigo2k** [comment]
+ for Ansible

**Comment by centminmod** [comment]
I haven't got my head around Ansible, Chef or Puppet to be honest, so would need help there. But yeah Ansible would be most likley candidate.

**Comment by nlemoine** [comment]
The idea was to convert the whole script into an Ansible playbook. Not just use Ansible to download and execute the script.

Ansible is not only used to install/configure a machine but can also ensure that services are running, etc. It can be run multiple times whereas a bash script can't (at least, it's not recommended to).  

I'm aware it's a quite huge change but I wanted to suggest the idea. There are some good examples here: https://github.com/ansible/ansible-examples/tree/master/wordpress-nginx
And also some other example here and there: https://github.com/nganhtuan63/ansible-webstack-php-fpm-nginx-mysql-centos6

But unfortunately none are as good as centminmod. Combining Ansible and centminmod would be the perfect server management tool.

**Comment by centminmod** [comment]
While that would be great but converting entire script to Ansible playbook would be quite a big job heh. But using Ansible for post Centmin Mod service management should be easier to do.

**Comment by jeffwidman** [comment]
+1 for converting entire thing to Ansible. I prefer Ansible instead of Chef/Puppet/Salt.

Like the above poster, I looked into using Ansible for creating a nice LEMP stack, but George's custom tweaks are better, so I'm using Centminmod, but if there was a comparable Ansible script, I'd switch to it immediately--it's cleaner, more modular, and the idempotent aspect feels safer.

However, users would have to change variables in a text file instead of entering numbers on a menu screen. I don't think this is a bad thing, it's just different and might be a little bit of a hurdle for the less technically-inclined.

**Comment by jeffwidman** [comment]
I just open-sourced the Ansible roles I use to wrap centminmod for post-install configuration management:

https://github.com/jeffwidman/ansible-centminmod

**Comment by henryperkins** [comment]
It sounds on brand, and would put the product in Red Hat’s line of sight.
