### ISSUE TITLE
PCRE install fails (url needs updating)

### ISSUE THREAD

**Issue by atomGit** [centminmod/centminmod#41]
CentOS 6.5 x86 Minimal
centmin-v1.2.3-eva2000.07

install fails when downloading  pcre-8.37.tar.gz because the file does not exist (404 from sourceforge)

`Download pcre-8.37.tar.gz ...
--2015-07-06 10:22:09--  http://downloads.sourceforge.net/project/pcre/pcre/8.37/pcre-8.37.tar.gz
Resolving downloads.sourceforge.net... 216.34.181.59
Connecting to downloads.sourceforge.net|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-06 10:22:09 ERROR 404: Not Found.

Error: pcre-8.37.tar.gz download failed.
check Centmin Mod log for details at /root/centminlogs/
Aborting script...`

**Comment by centminmod** [comment]
thanks @atomGit for heads up, fixed in 123.07stable branch and site download zip 

replaced the old pcre mirror url with new one.

Might also want to check out .08 beta03 branch = 123.08beta03 lots of new features to play with https://community.centminmod.com/threads/centmin-mod-123-08beta03-branch-released.3110/ :)
