### ISSUE TITLE
support for lets encrypt

### ISSUE THREAD

**Issue by tuwid** [centminmod/centminmod#57]
Hi,
its quite a nice project and  I was wondering if you were planning to add lets encrypt auto-install features
Lets encrypt lets you get a free ssl cert by doing a webcheck verification

**Comment by morloderex** [comment]
It already has support for letsencrypt. Look at some of the branches of the project.

**Comment by tuwid** [comment]
@morloderex link ?

**Comment by morloderex** [comment]
[here you go](https://centminmod.com/acmetool)

**Comment by centminmod** [comment]
@tuwid @morloderex just in time as centmin mod letsencrypt integration addon acmetool.sh is about to begin public beta testing see https://community.centminmod.com/threads/official-acmetool-sh-testing-thread-for-centmin-mod-123-09beta01.8290/ :)

@morloderex the old branches are deprecated due to a total rewrite explained at https://centminmod.com/acmetool

**Comment by tuwid** [comment]
Thanks @centminmod @morloderex
