### ISSUE TITLE
Operations in SCREEN

### ISSUE THREAD

**Issue by tuwid** [centminmod/centminmod#65]
Hi,
i've been using this amazing product for some time now and often happens that my network connection would drop (dont ask, universe hates me ) so I was thinking that why the operations inside centmin arent done via screen ? A screen would allow the process to continue even if the user is disconnected

**Comment by centminmod** [comment]
Another nice question for the forums https://community.centminmod.com ;)  Which operations you talking about ? initial install ? You can do startup a screen session for that and then run initial install. Or you mean for nginx and php-fpm compiles ?

**Comment by tuwid** [comment]
@centminmod i was referring more to the initial setup as if that goes wrong on that phase you have to redo the server over..
Also would be nice to have in other processes but mostly in the init but the point is that i always forget to do that (dunno why just has a tendency to slip my mind) and since it happened to me a couple of times i recalled that many installers do that (they run inside a screen ) 
I guess you can also put a reminder or something

**Comment by centminmod** [comment]
answering at https://community.centminmod.com/threads/operations-in-screen-65.9799/#post-41720

**Comment by sflcnetwork** [comment]
I have the same "issue" (due to a spotty connection where I am geographically at the moment), this isn't a centminmod bug/problem, your ssh connection is terminated abruptly, that's your issue and what you were doing at the time will of course abruptly come to an end, whether you were adding a domain, generating a self-signed cert, recompiling nginx or just sitting on htop.

Ultimately, what I recommend is this:

yum install tmux

after tmux is installed, type: 

tmux

and do whatever you want

if your session is abruptly disconnected, tmux will keep doing whatever you were doing at the time, then reconnect via ssh, then type:

tmux attach -t 0

and you're back to what was happening before.

I recommend this "issue" be closed as it's not an bug with centminmod.

**Comment by tuwid** [comment]
@sflcnetwork its not a bug its more like a recommendation that that initial install to start with screen.
Anyway i'll try to remember to start screen/tmux next time
