### ISSUE TITLE
Documentations about `with-ld-opt` & `with-cc-opt`

### ISSUE THREAD

**Issue by concatime** [centminmod/centminmod#95]
Hi, could you provide some informations in the docs about the compile options.
```
--with-ld-opt='-ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib'
--with-cc-opt='-m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -gsplit-dwarf' 
```
I meen, I have absolutely no idea what each option means, and why it's useful in this context.

**Comment by centminmod** [comment]
Best to google search for each option as there's heaps of info out there. The basic gist is nginx is completed with jemalloc memory allocator instead of default glibc (google for jemalloc vs tcmalloc vs glibc) and compiled for Intel cpu 64bit march=native optimisation with nginx fastopen TCP support and optimal config for both compile speed and resulting nginx binaries performance.
